core:
        esm_runscripts:
                SimulationSetup:
                        - "_create_setup_folders"
                        - "_create_component_folders"
                        - "initialize_experiment_logfile"  
                        - "_write_finalized_config"
                        - "copy_tools_to_thisrun"
                        - "_copy_preliminary_files_from_experiment_to_thisrun"
                        - "_show_simulation_info"  

plugins:
        my_plugin:
                location: "/work/ollie/dbarbi/my_plugin"
                git-url: ""
                my_plugin:
                        - "write_something"

