model: yac
environment_changes:
        choose_computer.name:
                mistral:
                        add_module_actions:
                                - "load autoconf/2.69"
                                - "load automake/1.16.1"
                ollie:
                        add_module_actions:
                                - "load automake"

metadata:
    Information: "For more information about YAC please go to the webpage: https://dkrz-sw.gitlab-pages.dkrz.de/yac/index.html"
