# RECOM YAML CONFIGURATION FILE
#

model: recom
branch: master
version: 2.0

metadata:
        Institute: AWI
        Description:
                REcoM (Regulated Ecosystem Model) is an ecosystem and biogeochemistry model.
        Authors: Judith Hauck
        Publications:
                - "Seasonally different carbon flux changes in the Southern Ocean in response to the southern annular mode <https://doi.org/10.1002/2013GB004600>"
                - "Arctic Ocean biogeochemistry in the high resolution FESOM 1.4-REcoM2 model <https://doi.org/10.1016/j.pocean.2018.09.006>"
        License:
                Please make sure you have a licence to use REcoM. In case you are unsure,
                please contact redmine...

setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
data_path: ""


namelist_dir: "${esm_namelist_dir}/${model}"

namelists:
        - namelist.recom

namelist_changes:
        namelist.recom:
                pavariables:
                        REcoMDataPath: "${data_path}"


choose_lresume:
        true:
                add_namelist_changes:
                        namelist.recom:
                                pavariables:
                                        recom_restart: true
        false:
                add_namelist_changes:
                        namelist.recom:
                                pavariables:
                                        recom_restart: false

config_files:
        recom:  recom

config_sources:
        recom:  "${namelist_dir}/namelist.recom"


restart_in_files:
        bio_restart: bio_restart

restart_in_in_work:
        bio_restart: fesom.${parent_date!syear}.bio.nc

restart_in_sources:
        bio_restart: fesom.${parent_date!syear}.bio.nc

restart_out_files:
        bio_restart: bio_restart

restart_out_in_work:
        bio_restart: fesom.${end_date!syear}.bio.nc

restart_out_sources:
        bio_restart: fesom.${end_date!syear}.bio.nc


outputs: [diags3d01,diags3d02,CO2y,aCO2,rDIN,rDON,rDOC,rDSi,PAR,NPPn,NPPd,GPPn,GPPd,NNAn,NNAd,GNAn,GNAd,benCalc,benSi,benC,benN,denb,aN,aFe,Hp,CO2f,dpCO2s,pCO2s,bgc01,bgc02,bgc03,bgc04,bgc05,bgc06,bgc07,bgc08,bgc09,bgc10,bgc11,bgc12,bgc13,bgc14,bgc15,bgc16,bgc17,bgc18,bgc19,bgc20,bgc21,slp]


