# RECOM YAML CONFIGURATION FILE
#

model: recom
branch: master
version: 2.0

metadata:
        Institute: AWI
        Description:
                REcoM (Regulated Ecosystem Model) is an ecosystem and biogeochemistry model.
        Authors: Judith Hauck
        Publications:
                - "Seasonally different carbon flux changes in the Southern Ocean in response to the southern annular mode <https://doi.org/10.1002/2013GB004600>"
                - "Arctic Ocean biogeochemistry in the high resolution FESOM 1.4-REcoM2 model <https://doi.org/10.1016/j.pocean.2018.09.006>"
        License:
                Please make sure you have a licence to use REcoM. In case you are unsure,
                please contact redmine...

setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
