components:
- fesom-1.4-recom-mocsy-slp
- recom-2.0
coupling_changes:
- sed -i '/FESOM_COUPLED/s/ON/OFF/g' fesom-1.4-recom-mocsy-slp/CMakeLists.txt
- sed -i '/FESOM_RECOM/s/OFF/ON/g' fesom-1.4-recom-mocsy-slp/CMakeLists.txt
- sed -i '/RECOM_LIBRARY/s/OFF/ON/g' fesom-1.4-recom-mocsy-slp/CMakeLists.txt
