esm-software:
        "esm-tools":
                git-repository: "gitlab.dkrz.de/esm-tools/esm-tools.git"
                available_versions:
                        - "r3"
        "esm-workshop":
                git-repository: "gitlab.dkrz.de/esm-tools/esm-workshop.git"
                available_versions:
                        - "Mai 2019"
        "esm-usermanual":
                git-repository: "gitlab.dkrz.de/esm-tools/esm-usermanual.git"
                available_versions:
                        - "r3"
        "git-workshop":
                git-repository: "gitlab.dkrz.de/esm-tools/git-workshop.git"
                available_versions:
                        - "Mai 2019"


defaults:                          
        comp_command: 'mkdir -p build; cd build; cmake ..;   make install -j `nproc --all`'
        clean_command: 'rm -rf build CMakeCache.txt'
               

components:
        "amip":
                git-repository: "gitlab.dkrz.de/ec-earth/amip-forcing.git"
                comp_command: "mkdir bin; cd src; make"
                clean_command: "rm -rf bin; cd src; make clean"

        "echam":
                install_bins: "src/echam/bin/echam6"
                git-repository: "https://gitlab.dkrz.de/modular_esm/echam6.git"
                branch: "${echam.version}"
                available_versions:
                        - "6.3.04p1"
                        - "6.3.02p4"
                        - "6.3.05p2"  
                comp_command: "${defaults.comp_command}"
                clean_command: "${defaults.clean_command}"
                choose_version:
                        "6.3.05p2":
                                git-repository: "https://gitlab.dkrz.de/foci/src/echam.git"
                                branch: "esm-tools"
        "fesom":
                choose_version: 
                        "1.4":
                                git-repository: "https://gitlab.dkrz.de/modular_esm/fesom-1.4.git"
                                install_bins: "bin/fesom"
                        "2.0":
                                git-repository: 
                                        - "https://gitlab.dkrz.de/FESOM/fesom2.git"
                                        - "github.com/FESOM/fesom2.git"
                                branch: "2.0.2"
                                install_bins: "bin/fesom.x"
                available_versions:
                        - "1.4"
                        - "2.0"
                comp_command: "${defaults.comp_command}"
                clean_command: "${defaults.clean_command}"

        "fesom_mesh_part":
                install_bins: "bin/fesom.x.ini"
                choose_version: 
                        1.4:
                                git-repository: "https://gitlab.dkrz.de/modular_esm/fesom-1.4.git"
                        2.0:
                                git-repository: 
                                        - "https://gitlab.dkrz.de/FESOM/fesom2.git"
                                        - "github.com/FESOM/fesom2.git"
                                branch: "2.0.2"
                available_versions:
                        - "1.4"
                        - "2.0"
                comp_command: "cd mesh_part; mkdir build -p; cd build; cmake ..; make install -j `nproc --all`"
                clean_command: "rm -rf bin/fesom.x.ini mesh_part/build mesh_part/CMakeCache.txt"
        
        "icon":
                git-repository: "gitlab.dkrz.de/modular_esm/ICON-ATM.git"
                branch: "${icon.version}"
                conf_command: "./configure --with-fortran=gcc --with-openmp --with-grib_api"
                comp_command: "make -j `nproc --all"
                clean_command: "make distclean" 
                available_versions:
                        - "2.1.0"
                        - "2.3.0-nwp5"
                        - "2.4.0"
        
        "metos3d":
                git-repository: "https://github.com/metos3d/metos3d.git"
                git-subrepositories: 
                        - "https://github.com/metos3d/simpack.git"
                        - "https://github.com/metos3d/model.git"
                comp_command: "${defaults.comp_command}"
                clean_command: "${defaults.clean_command}"

        "metos3d-data":                  
                git-repository: "https://github.com/metos3d/data.git"
                comp_command: "cd data/data; gunzip -c TMM.tar.gz > TMM.tar; tar xf TMM.tar; rm -f TMM.tar"

        "nemo":
                version: 3.6-ogcm
                available_versions:
                        - "3.6foci"
                        - "3.6-ogcm"  
                git-repository: "https://gitlab.dkrz.de/foci/src/NEMOGCM.git"
                branch: "esm-tools"
                destination: "nemo-3.6"
                comp_command: "export NEMO_TOPLEVEL=${model_dir}; cd CONFIG; ./makenemo -n ${grid} -m ${computer.nemoarchfile} -j 24"
                clean_command: "cd CONFIG; ./makenemo -n ${nemo.grid} clean"
                install_bins: "CONFIG/${nemo.grid}/BLD/bin/nemo.exe"
                requires:
                        - xios-2.0_r982
                choose_nemo.version:
                        "3.6-ogcm":
                                grid: "GYRE_XIOS"
                        "3.6foci":
                                git-repository: "https://gitlab.dkrz.de/foci/src/nemo.git"
                                grid: "ORCA05_LIM2_KCM_AOW"
        "oasis3-mct":
                install_libs: 
                        - "build/lib/psmile/libpsmile.a"
                        - "build/lib/psmile/mct/libmct.a"
                        - "build/lib/psmile/mct/mpeu/libmpeu.a"
                        - "build/lib/psmile/scrip/libscrip.a"
                comp_command: 'mkdir -p build; cd build; cmake ..;   make -j `nproc --all`'
                clean_command: "${defaults.clean_command}"
                git-repository: "https://gitlab.dkrz.de/modular_esm/oasis3-mct.git"
                destination: "oasis"
                available_versions:
                        - "foci"
                        - "ec-earth"
                        - "4.0"
                choose_version:
                        "ec-earth":
                                branch: "ec-earth-version"
                        "foci":
                                git-repository: "https://gitlab.dkrz.de/foci/src/oasis3mct.git"
                                branch: "esm-tools"
                        "4.0":
                                git-repository: "https://gitlab.dkrz.de/b350090/oasis3-mct4.git"
                                branch: "fociagrif"

                # make sure all oasis versions are in the repo, with correct version branches          
        
        "oifs":
                install_bins: "make/esm/oifs/bin/master.exe"
                comp_command: "cd make; ../fcm/bin/fcm make -v -j8 -f oifs.cfg"
                clean_command: "rm -rf make/esm"                
                git-repository: "https://gitlab.dkrz.de/modular_esm/oifs-40r1.git"        
                choose_version:
                        40r1:
                                branch: "foci_conserv"
                        40r1-foci:
                                branch: "dirk_on_mistral"
                                destination: "40r1"
                        40r1-agcm:
                                compile_command: "export OIFS_COMP=agcm; cd make; ../fcm/bin/fcm make -v -j8 -f oifs-agcm.cfg"
                available_versions:
                        - "40r1"
                        - "40r1-foci"                
                        - "40r1-agcm"                
        
        "pism":
                comp_command: "mkdir -p build; cd build; cmake .. -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
                clean_command: "${defaults.clean_command}"
                choose_version:
                        snowflake0.7:
                                git-repository: "swrepo1.awi.de/scmrepos/git/snowflake/snowflake.git"        
                                branch: "awi0.7-dev"
                        snowflake1.0:
                                git-repository: "swrepo1.awi.de/scmrepos/git/snowflake/snowflake.git"        
                                branch: "stable1.0-awi-dev"
                available_versions:
                        - "snowflake0.7"
                        - "snowflake1.0"  
        
        "recom":
                git-repository: "gitlab.dkrz.de/modular_esm/recom.git"
                branch: "modular"
                destination: "recom"
                available_versions:
                        - "2.0"
                comp_command: "${defaults.comp_command}"
                clean_command: "${defaults.clean_command}"
        
        "rnfmap":
                install_bins: "bin/rnfmap.exe"
                comp_command: "rm -rf bin; mkdir bin; cd src; make"
                clean_command: "rm -rf bin; cd src; make clean"
                available_versions: 
                        - "ec-earth"
                        - "focioifs"  
                git-repository: "gitlab.dkrz.de/ec-earth/runoff-mapper.git"
                choose_version:
                        "ec-earth":
                                branch: "esm-tools"
                        "focioifs":
                                branch: "esm-tools-focioifs"
        
        "vilma":
                git-repository: "gitlab.dkrz.de/modular_esm/vilma.git vilma_1d"
                available_versions:
                        - "1d"
                comp_command: "${defaults.comp_command}"
                clean_command: "${defaults.clean_command}"
        
        "xios":
                install_bins: "bin/xios_server.exe"
                available_versions:
                        - "2.0_r982"
                        - "ogcm"  
                git-repository: "https://gitlab.dkrz.de/foci/src/xios.git"
                branch: "esm-tools"
                comp_command: "export XIOS_TOPLEVEL=${model_dir}; ./make_xios --arch ${computer.xiosarchfile} --netcdf_lib netcdf4_par --full --job 24"
                clean_command: "rm -rf bin lib obj ppsrc"
                choose_version:
                        "ogcm":
                                compile_command: "export XIOS_TOPLEVEL=${model_dir}; ./make_xios --arch ${computer.xiosarchfile} --netcdf_lib netcdf4_par --full --job 24"
                        "2.0_r982":
                                nothing: much

couplings:
        "fesom-1.4+echam-6.3.04p1":
                components:
                        - "echam-6.3.04p1"
                        - "fesom-1.4"
                        - "oasis3-mct-4.0" 
                coupling_changes:
                        - "sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-1.4/CMakeLists.txt"
                        - "sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt"

        "fesom-2.0+echam-6.3.04p1":
                components:
                        - "echam-6.3.04p1"
                        - "fesom-2.0"
                        - "oasis3-mct-4.0"
                coupling_changes:
                        - "sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt"
                        - "sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt"

        "fesom-2.0+oifs-40r1":
                components:
                        - "oifs-40r1"
                        - "fesom-2.0"
                        - "oasis3-mct-ec-earth" 

        "fesom-1.4+recom":
                components:
                        - "fesom-1.4"
                        - "recom-2.0"
                coupling_changes:
                        - "sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-1.4/CMakeLists.txt"
                        - "sed -i '/FESOM_RECOM/s/OFF/ON/g' fesom-1.4/CMakeLists.txt"
                        - "sed -i '/RECOM_LIBRARY/s/OFF/ON/g' fesom-1.4/CMakeLists.txt"  

        "fesom-2.0+recom":
                components:
                        - "fesom-2.0"
                        - "recom-2.0"
                coupling_changes:
                        - "sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt"
                        - "sed -i '/FESOM_RECOM/s/OFF/ON/g' fesom-2.0/CMakeLists.txt"
                        - "sed -i '/RECOM_LIBRARY/s/OFF/ON/g' fesom-2.0/CMakeLists.txt"  
        
        "nemo-3.6foci+echam-6.3.05p2":
                components:
                        - "echam-6.3.05p2"
                        - "nemo-3.6foci"
                        - "oasis3-mct-foci"
                coupling_changes:
                        - "sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.05p2/CMakeLists.txt"
                                        
        "nemo-3.6foci+oifs40r1-foci":
                components:
                        - "oifs-40r1-foci"
                        - "nemo-3.6foci"
                        - "oasis3-mct-foci"
                        - "rnfmap-focioifs"
                prepend_compile_command: "export FOCI_TOPLEVEL=${setup_dir}" 

        "nemo-3.6foci+oifs40r1-foci-o3":
                components:
                        - "oifs-40r1-foci"
                        - "nemo-3.6foci"
                        - "oasis3-mct-ec-earth"
                        - "rnfmap-focioifs"
                prepend_compile_command: "export FOCI_TOPLEVEL=${setup_dir}" 

        "nemo-3.6foci+oifs40r1":
                components:
                        - "oifs-40r1"
                        - "nemo-3.6foci"
                        - "oasis3-mct-foci"
                        - "rnfmap-focioifs"
                prepend_compile_command: "export FOCI_TOPLEVEL=${setup_dir}" 

        "nemo-3.6foci+oifs40r1-foci-o4":
                components:
                        - "oifs-40r1-foci"
                        - "nemo-3.6foci"
                        - "oasis3-mct-4.0"
                        - "rnfmap-focioifs"
                prepend_compile_command: "export FOCI_TOPLEVEL=${setup_dir}" 


        "pism-snowflake1.0+echam-6.3.04p1":
                components:
                        - "echam-6.3.04p1"
                        - "pism-snowflake1.0"
                          # - "scope"

        "pism-snowflake1.0+fesom-1.4":
                components:
                        - "fesom-1.4"
                        - "pism-snowflake1.0"
                          #- "scope"

        "oifs-40r1+amip":
                components:
                        - "oifs-40r1"
                        - "amip"
                        - "oasis3-mct-4.0"        
                coupling_changes:
                        - "sed -i '/COUPLENEMOECE = /s/.FALSE./.TRUE./g' oifs-40r1/src/ifs/module/yommcc.F90"
                        - "sed -i '/COUPLEFESOM2 = /s/.TRUE./.FALSE./g' oifs-40r1/src/ifs/module/yommcc.F90"

        "oifs-40r1+oasis":
                components: 
                        - "oifs-40r1"
                        - "oasis3-mct-4.0"
                coupling_changes: 
                        - "sed -i '/COUPLENEMOECE = /s/.FALSE./.TRUE./g' oifs-40r1/src/ifs/module/yommcc.F90"
                        - "sed -i '/COUPLEFESOM2 = /s/.TRUE./.FALSE./g' oifs-40r1/src/ifs/module/yommcc.F90"


setups:
        awicm:
                available_versions: 
                        - "1.0"
                        - "CMIP6"
                        - "2.0"
                choose_version:
                        "1.0":
                                couplings:                        
                                        - "fesom-1.4+echam-6.3.04p1"
                        "CMIP6":
                                couplings:                        
                                        - "fesom-1.4+echam-6.3.04p1"
                        "2.0":
                                couplings:                        
                                        - "fesom-2.0+echam-6.3.04p1"
                        "3.0":
                                couplings:                        
                                        - "fesom-2.0+oifs-40r1"

        awicm-recom:
                available_versions:
                        - "1.0"
                choose_version:
                        "1.0":
                                couplings:
                                        - "fesom-1.4+echam-6.3.04p1"
                                        - "fesom-1.4+recom"

        fesom-recom:
                available_versions:
                        - "1.4"
                        - "2.0"  
                choose_version:
                        "1.0":
                                couplings:
                                        - "fesom-1.4+recom"
                        "2.0":
                                couplings:
                                        - "fesom-2.0+recom"
        "foci":
                available_versions:
                        - "1.0"
                choose_version:
                        "1.0":
                                couplings:
                                        - "nemo-3.6foci+echam-6.3.05p2"

        focioifs:
                available_versions:
                        - vvl
                        - vvl-o3
                        - vvl-o3-awi3
                        - vvl-o4
                choose_version:
                        vvl:
                                couplings: 
                                        - "nemo-3.6foci+oifs40r1-foci"
                                nemo:
                                        version: 3.6foci
                                oifs:
                                        version: 40r1-foci
                                rnfmap: 
                                        version: focioifs
                                oasis3-mct:
                                        version: foci       
                        vvl-o3:          
                                couplings: 
                                        - "nemo-3.6foci+oifs40r1-foci-o3"
                                nemo:
                                        version: 3.6foci
                                oifs:
                                        version: 40r1-foci
                                rnfmap: 
                                        version: focioifs
                                oasis3-mct:
                                        version: ec-earth
                        vvl-o3-awi3:          
                                couplings: 
                                        - "nemo-3.6foci+oifs40r1"
                                nemo:
                                        version: 3.6foci
                                oifs:
                                        version: 40r1
                                rnfmap: 
                                        version: focioifs
                                oasis3-mct:
                                        version: foci       
                        vvl-o4:          
                                couplings: 
                                        - "nemo-3.6foci+oifs40r1-foci-o4"
                                nemo:
                                        version: 3.6foci
                                oifs:
                                        version: 40r1-foci
                                rnfmap: 
                                        version: focioifs
                                oasis3-mct:
                                        version: "4.0"       
                
        oifsamip:
                couplings:
                        - "oifs-40r1+amip"

        oifscl: 
                couplings:
                        - "oifs-40r1+oasis"
