#########################################################################################
######################### MPIESM YAML CONFIGURATION FILE ################################
#########################################################################################

general:
        model: mpiesm
        #model_dir: ${esm_master_dir}/mpiesm-${version}

        coupled_setup: True

        include_models:
                - echam
                - mpiom
                - oasis3mct

        version: "1.2"
        post_time: "00:60:00"
        choose_general.resolution:
                T31_GR30:
                        compute_time: "00:60:00"
                T63_GR15:
                        compute_time: "00:60:00"

choose_lresume:
        true:
                echam:
                        pseudo_resume_date: $(( ${echam.start_date} - ${echam.time_step}))
                        pseudo_end_date: $(( ${echam.next_date} - ${echam.time_step}))

forcing_sources:
        lctlib: "${model_dir}/util/running/adjunct_files/jsbach/lctlib_nlct21.def"


#########################################################################################

echam:

        choose_general.resolution:
                T31_GR30:
                        nproca: 24
                        nprocb: 18
                T63_GR15:
                        nproca: 24
                        nprocb: 24


#########################################################################################

mpiom:

        choose_general.resolution:
                T31_GR30:
                        nproca: 18
                        nprocb: 12
                T63_GR15:
                        nproca: 16
                        nprocb: 24

#########################################################################################

oasis3mct:
        
        model_dir: ${general.model_dir}/oasis

        process_ordering: #V1?
                - mpiom
                - echam

        o2a_lag: 2700 #V2?
        a2o_lag: 400 #V4?
        o2a_seq: 1 #V3?
        a2o_seq: 1 #V3?

        coupling_time_step: 86400

        coupling_directions:
                'mpiom->atmo':
                        lag: ${o2a_lag}
                        seq: ${o2a_seq}
                'atmo->mpiom':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}
