# XIOS YAML CONFIGURATION FILE
#
#

model: xios

metadata:
        Institute: IPSL and CEA
        Description:
                A library dedicated to I/O management in climate codes.
        Authors: Yann Meurdesoif (yann.meurdesoif@cea.fr)
        Publications:
        License:
                Please make sure you have a licence to use XIOS. In case you are
                unsure, please contact redmine...

executable: xios_server.exe
