# XIOS YAML CONFIGURATION FILE
#
#

model: xios
version: 2.0r982 
executable: xios.x

setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
xml_dir: ${nemo.model_dir}/CONFIG/${nemo.nemoconfig}/EXP00

config_files:
        domain_def: domain_def
        field_def: field_def
        file_def: file_def
        io_def: io_def

config_sources:
        domain_def: ${xml_dir}/domain_def.xml
        field_def: ${xml_dir}/field_def.xml
        file_def: ${xml_dir}/file_def.xml
        io_def: ${xml_dir}/iodef.xml

bin_sources:
        server: ${bin_dir}/xios.x
