model: fesom_mesh_part
version: "2.0"


setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
namelist_dir: "${esm_namelist_dir}/fesom2/"

pool_dir: "${computer.pool_directories.pool}"
mesh_dir: "${pool_dir}/meshes/mesh_CORE2_final/"

executable: fesom_ini
namelists:
    - "namelist.config"

bin_in_work:
    fesom_ini: "${executable}"

bin_sources:
    fesom_ini: ${bin_dir}/${executable}

input_files:
    aux3d: aux3d
    nod2d: nod2d
    elem2d: elem2d
    nodhn: nodhn

input_sources:
    aux3d: ${mesh_dir}/aux3d.out
    nod2d: ${mesh_dir}/nod2d.out
    elem3d: ${mesh_dir}/elem2d.out
    nodhn: ${mesh_dir}/nodhn.out
