# OIFS standalone (=AMIP?) YAML FILE
#

executable: master.exe
command: ${executable} -v ecmwf -e ${general.expid}
version: 40r1

input_expid: ECE3

wam: True
wam_2w: True
wam_step: 1
read_icmcl: 0
generate_namelist: 1
ensemble: 0
ensemble_id: 1
post_processing: 0

cmip6: True
cmip5: False
cmip6_scenario: "historical"
cmip5_scenario: 0
cmip_fix_year: 0
a4xco2: False
onepctco2: False
lhvolca: False

supercooled_liquid_could_fix: 0
dr_hook_ignore_signals: -1

orb_switch: False
orb_mode: "variable_year"
orb_iyear: ${initial_date!syear} # ??? original : $(date -u -d "${run_start_date}" +%Y)

restart: 12
restart_rate: 12
restart_unit: 'months'

threads: 1
levels: L91
res: T255
ny: 1

hours: ""

#model_dir: ${esm_master_dir}/oifs-${version}
bin_dir: ${model_dir}/bin
input_dir: ${computer.pool_directories.pool}/oifs-${version}/${res}${levels}/
rtables_dir: ${input_dir}/../rtables/
forcing_dir: ${input_dir}/../${version}/ifsdata
namelist_dir: ${esm_namelist_dir}/oifs
cmip6_data_dir: ${input_dir}/../cmip6_data
cmip5_data_dir: ${input_dir}/../cmip5_data

choose_res:
        T95:
                nx: 13280
                time_step: 3600
                OASIS_GRID_name: "048"
                res_number: 95
                res_number_tl: ""
        T159:
                nx: 35718
                time_step: 3600
                OASIS_GRID_name: "080"
                res_number: 159
                res_number_tl: ""
        TL159:
                nx: 35718
                time_step: 3600
                OASIS_GRID_name: "080"
                res_number: L159
                res_number_tl: 159
        T255:
                nx: 88838
                time_step: 2700
                OASIS_GRID_name: "128"
                res_number: 255
                res_number_tl: ""
        T511:
                nx: 348528
                time_step: 900
                OASIS_GRID_name: "256"
                res_number: 511
                res_number_tl: ""
        T799:
                nx: 843490
                time_step: 600
                OASIS_GRID_name: "400"
                res_number: 799
                res_number_tl: ""
        T1279:
                nx: 2140702
                time_step: 600
                OASIS_GRID_name: "640"
                res_number: 799
                res_number_tl: ""



oasis_grid_name_a: "A${oasis_grid_name}"
oasis_grid_name_r: "R${oasis_grid_name}"
oasis_grid_name_l: "L${oasis_grid_name}"


choose_wam:
        1:
                add_input_files:
                        wam_grid_tables: wam_grid_tables
                        wam_subgrid_0: wam_subgrid_0
                        wam_subgrid_1: wam_subgrid_1
                        wam_subgrid_2: wam_subgrid_2
                        uwavein: uwavein
                        specwavein: specwavein
                        sfcwindin: sfcwindin
                        cdwavein: cdwavein


choose_levels:
        L91:
                levels_number: 91

export_vars:
        OIFS_EXPID: ${general.expid}


bin_sources: ${bin_dir}/${executable}

input_files:
        ICMGG_INIT: ICMGG_INIT
        ICMGG_INIUA: ICMGG_INIUA
        ICMSH_INIT: ICMSH_INIT
        # still missing: rtables/*, globbing not available yet (fix!)
        # also missing: modify_init for ensemble stuff

input_sources:
        ICMGG_INIT: ${input_dir}/${start_date!syear!smonth!sday}${hours}/ICMGG${input_expid}INIT
        ICMGG_INIUA: ${input_dir}/${start_date!syear!smonth!sday}${hours}/ICMGG${input_expid}INIUA
        ICMSH_INIT: ${input_dir}/${start_date!syear!smonth!sday}${hours}/ICMSH${input_expid}INIT
        wam_grid_tables: ${input_dir}/${start_date!syear!smonth!sday}${hours}/wam_grid_tables
        wam_subgrid_0: ${input_dir}/${start_date!syear!smonth!sday}${hours}/wam_subgrid_0
        wam_subgrid_1: ${input_dir}/${start_date!syear!smonth!sday}${hours}/wam_subgrid_1
        wam_subgrid_2: ${input_dir}/${start_date!syear!smonth!sday}${hours}/wam_subgrid_2
        uwavein: ${input_dir}/${start_date!syear!smonth!sday}${hours}/uwavein
        specwavein: ${input_dir}/${start_date!syear!smonth!sday}${hours}/specwavein
        sfcwindin: ${input_dir}/${start_date!syear!smonth!sday}${hours}/sfcwindin
        cdwavein: ${input_dir}/${start_date!syear!smonth!sday}${hours}/cdwavein

input_in_work:
        ICMGG_INIT: ICMGG${expid}INIT
        ICMGG_INIUA: ICMGG${expid}INIUA
        ICMSH_INIT: ICMSH${expid}INIT



environment_changes:
        add_export_vars:        
                - 'PERL5LIB="/usr/lib64/perl5"'
                - 'PATH=$PATH:/home/ollie/jstreffi/fcm/bin/'

                - 'OIFS_GRIB_INCLUDE=-I/home/ollie/jstreffi/ecmwf/grib_api/include'
                - 'OIFS_GRIB_LIB="-L/home/ollie/jstreffi/ecmwf/grib_api/lib -lgrib_api_f90 -lgrib_api"'
                - 'OIFS_GRIB_BIN="/home/ollie/jstreffi/ecmwf/grib_api/bin"'

                - 'LAPACK_LIB_DEFAULT="-L/global/AWIsoft/intel/2018/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential"'
                - 'OIFS_OASIS_BASE=${model_dir}/../lib'
                - 'OIFS_OASIS_INCLUDE=-I$OIFS_OASIS_BASE/../oasis/build/lib/psmile'
                - 'OIFS_OASIS_LIB="-L$OIFS_OASIS_BASE -lpsmile -lmct -lmpeu -lscrip"'

                - 'OIFS_NETCDF_LIB="-L$NETCDF_DIR/lib -lnetcdf"'
                - 'OIFS_NETCDF_INCLUDE=-I$NETCDF_DIR/include'
                - 'OIFS_NETCDFF_LIB="-L$NETCDF_DIR/lib -lnetcdff"'
                - 'OIFS_NETCDFF_INCLUDE=-I$NETCDF_DIR/include'

                - 'OIFS_FC=$FC'
                - 'OIFS_FFLAGS="-r8 -fp-model precise -align array32byte -O3 -xCORE_AVX2 -g -traceback -convert big_endian"'
                - 'OIFS_FFIXED=""'
                - 'OIFS_FCDEFS="BLAS LITTLE LINUX INTEGER_IS_INT"'


                - 'OIFS_CC=$CC'
                - 'OIFS_CFLAGS="-fp-model precise -O3 -xCORE_AVX2 -g -traceback -qopt-report=0"'
                - 'OIFS_CCDEFS="LINUX LITTLE INTEGER_IS_INT _ABI64 BLAS"'
