# OIFS standalone (=AMIP?) YAML FILE
#

model: oifs
executable: master.exe
command: ${executable} -v ecmwf -e ${oifs.input_expid}
version: 40r1
type: atmosphere

description: |
        OpenIFS based on IFS cycle 40 release 1, ECMWF
        Carver et al., in prep.

license_text: |
        ECMWF license. AWI and GEOMAR have licenses. 

# Default is TL159L91 
# Forcing from gu5a prepIFS forcing
input_expid: ECE3
resolution: TL159
levels: L91
prepifs_expid: gu5a
prepifs_startdate: 19820101
mip: "cmip5"
scenario: "historical"
output: "default"

wam: True
wam_2w: True
wam_step: 1
read_icmcl: 0
generate_namelist: 1
ensemble: 0
ensemble_id: 1
post_processing: 0

cmip6: True
cmip5: False
cmip6_scenario: "historical"
cmip5_scenario: 0
cmip_fix_year: 0
a4xco2: False
onepctco2: False
lhvolca: False

supercooled_liquid_could_fix: 0
dr_hook_ignore_signals: -1

orb_switch: False
orb_mode: "variable_year"
orb_iyear: ${initial_date!syear} # ??? original : $(date -u -d "${run_start_date}" +%Y)

restart: 12
restart_rate: 12
restart_unit: 'months'

threads: 1
ny: 1

hours: "00"

#model_dir: ${esm_master_dir}/oifs-${version}
model_dir: ${general.model_dir}
bin_dir: ${model_dir}/bin
pool_dir: "${computer.pool_directories.pool}"
input_dir: ${pool_dir}
rtables_dir: ${input_dir}/../rtables/
vtables_dir: ${input_dir}/../vtables/
clim_dir: ${input_dir}/../
forcing_dir: ${input_dir}/../${version}/ifsdata/
namelist_dir: ${esm_namelist_dir}/oifs
cmip6_data_dir: ${input_dir}/../cmip6_data
cmip5_data_dir: ${input_dir}/../cmip5_data

namelists:
        - fort.4

choose_resolution:
        TQ95:
                nx: 13280
                time_step: 3600
                oasis_grid_name: "048"
                res_number: 95
                res_number_tl: ""
        TL159:
                nx: 35718
                time_step: 3600
                oasis_grid_name: "080"
                res_number: 159
                res_number_tl: "159l_2"
        TCO159:
                nx: 35718
                time_step: 3600
                oasis_grid_name: "080"
                res_number: 159
                res_number_tl: 159l_2
        TL255:
                nx: 88838
                time_step: 2700
                oasis_grid_name: "128"
                res_number: 255
                res_number_tl: "255l_2"
        TL511:
                nx: 348528
                time_step: 900
                oasis_grid_name: "256"
                res_number: 511
                res_number_tl: "511l_2"
        TL799:
                nx: 843490
                time_step: 600
                oasis_grid_name: "400"
                res_number: 799
                res_number_tl: "799l_2"
        TL1279:
                nx: 2140702
                time_step: 600
                oasis_grid_name: "640"
                res_number: 799
                res_number_tl: "1279l_2"

choose_computer.cores_per_node:
        24:
                nproca: 96
                nprocb: 1
        36:
                nproca: 108
                nprocb: 1
        48:
                nproca: 96
                nprocb: 1
                

before_step: 0
next_step: 744
steps_per_day: "$(( 86400 / ${time_step} ))"
lresume: false

restart_rate: 1
restart_unit: "months"

oasis_grid_name_a: "A${oasis_grid_name}"
oasis_grid_name_r: "R${oasis_grid_name}"
oasis_grid_name_l: "L${oasis_grid_name}"


choose_wam:
        1:
                add_input_files:
                        wam_grid_tables: wam_grid_tables
                        wam_subgrid_0: wam_subgrid_0
                        wam_subgrid_1: wam_subgrid_1
                        wam_subgrid_2: wam_subgrid_2
                        uwavein: uwavein
                        specwavein: specwavein
                        sfcwindin: sfcwindin
                        cdwavein: cdwavein
                        
                namelist_changes:
                        fort.4:
                                LWCOU: ".true."
                                LWCOU2W: ".true."
                        
        0:
                namelist_changes:
                        fort.4:
                                LWCOU: ".false."
                                LWCOU2W: ".false." 
                        

choose_levels:
        L91:
                levels_number: 91
        L137:
                levels_number: 137

export_vars:
        OIFS_EXPID: ${oifs.input_expid}


bin_sources: 
        bin: ${bin_dir}/${executable}

input_files:
        ICMGG_INIT: ICMGG${oifs.input_expid}INIT
        ICMGG_INIUA: ICMGG${oifs.input_expid}INIUA
        ICMSH_INIT: ICMSH${oifs.input_expid}INIT
        rtables: rtables
        vtables: vtables
        # still missing: rtables/*, globbing not available yet (fix!)
        # also missing: modify_init for ensemble stuff

forcing_files:
        choose_mip:
                "cmip5":
                        PRE2005_MIDYR_CONC: PRE2005_MIDYR_CONC
                        RCP3PD_MIDYR_CONC: RCP3PD_MIDYR_CONC
                        RCP45_MIDYR_CONC: RCP45_MIDYR_CONC
                        RCP6_MIDYR_CONC: RCP6_MIDYR_CONC
                        RCP85_MIDYR_CONC: RCP85_MIDYR_CONC
        
        choose_version:
                40r1:
                        C11CLIM: C11CLIM
                        C12CLIM: C12CLIM 
                        C22CLIM: C22CLIM
                        CCL4CLIM: CCL4CLIM
                        CH4CLIM: CH4CLIM
                        CO2CLIM: CO2CLIM
                        ECOZC: ECOZC
                        GCH4CLIM: GCH4CLIM
                        GCO2CLIM: GCO2CLIM
                        GOZOCLIM: GOZOCLIM
                        MCICA: MCICA
                        N2OCLIM: N2OCLIM
                        NO2CLIM: NO2CLIM
                        OZOCLIM: OZOCLIM 
                        RADRRTM: RADRRTM
                        RADSRTM: RADSRTM
                        
                        
choose_scenario:
        "amip-prepifs":
                forcing_files:
                        sst: ICMCL${expid}INIT
        "amip":
                forcing_files:
                        sst: ICMCL${expid}INIT_CMIP6
        "highresmip":
                forcing_files:
                        sst: ICMCL${expid}INIT_HIGHRESMIP
        "historical":
                namelist_changes:
                        fort.4:
                                NAMCMIP:
                                        LGHGCMIP5: ".true."
        "piControl":
                namelist_changes:
                        fort.4:
                                NAMCMIP:
                                        LGHGPI: ".true."


input_sources:
        ICMGG_INIT: ${input_dir}/${prepifs_startdate}${hours}/ICMGG${prepifs_expid}INIT
        ICMGG_INIUA: ${input_dir}/${prepifs_startdate}${hours}/ICMGG${input_expid}INIUA
        ICMSH_INIT: ${input_dir}/${prepifs_startdate}${hours}/ICMSH${input_expid}INIT
        wam_grid_tables: ${input_dir}/${prepifs_startdate}${hours}/wam_grid_tables
        wam_subgrid_0: ${input_dir}/${prepifs_startdate}${hours}/wam_subgrid_0
        wam_subgrid_1: ${input_dir}/${prepifs_startdate}${hours}/wam_subgrid_1
        wam_subgrid_2: ${input_dir}/${prepifs_startdate}${hours}/wam_subgrid_2
        uwavein: ${input_dir}/${prepifs_startdate}${hours}/uwavein
        specwavein: ${input_dir}/${prepifs_startdate}${hours}/specwavein
        sfcwindin: ${input_dir}/${prepifs_startdate}${hours}/sfcwindin
        cdwavein: ${input_dir}/${prepifs_startdate}${hours}/cdwavein
        rtables: ${rtables_dir}/*
        vtables: ${vtables_dir}/*

forcing_sources:
        # GHG data
        PRE2005_MIDYR_CONC: ${cmip5_data_dir}/PRE2005_MIDYR_CONC.txt
        RCP3PD_MIDYR_CONC: ${cmip5_data_dir}/RCP3PD_MIDYR_CONC.txt
        RCP45_MIDYR_CONC: ${cmip5_data_dir}/RCP45_MIDYR_CONC.txt
        RCP6_MIDYR_CONC: ${cmip5_data_dir}/RCP6_MIDYR_CONC.txt
        RCP85_MIDYR_CONC: ${cmip5_data_dir}/RCP85_MIDYR_CONC.txt
        # ifsdata
        C11CLIM: ${forcing_dir}/ifsdata/C11CLIM
        C12CLIM: ${forcing_dir}/ifsdata/C12CLIM 
        C22CLIM: ${forcing_dir}/ifsdata/C22CLIM
        CCL4CLIM: ${forcing_dir}/ifsdata/CCL4CLIM
        CH4CLIM: ${forcing_dir}/ifsdata/CH4CLIM
        CO2CLIM: ${forcing_dir}/ifsdata/CO2CLIM
        ECOZC: ${forcing_dir}/ifsdata/ECOZC
        GCH4CLIM: ${forcing_dir}/ifsdata/GCH4CLIM
        GCO2CLIM: ${forcing_dir}/ifsdata/GCO2CLIM
        GOZOCLIM: ${forcing_dir}/ifsdata/GOZOCLIM
        MCICA: ${forcing_dir}/ifsdata/MCICA
        N2OCLIM: ${forcing_dir}/ifsdata/N2OCLIM
        NO2CLIM: ${forcing_dir}/ifsdata/NO2CLIM
        OZOCLIM: ${forcing_dir}/ifsdata/OZOCLIM 
        RADRRTM: ${forcing_dir}/ifsdata/RADRRTM
        RADSRTM: ${forcing_dir}/ifsdata/RADSRTM

input_in_work:
        ICMGG_INIT: ICMGG${expid}INIT
        ICMGG_INIUA: ICMGG${expid}INIUA
        ICMSH_INIT: ICMSH${expid}INIT
        rtables: rtables/*
        vtables: vtables/*

forcing_in_work:
        PRE2005_MIDYR_CONC: PRE2005_MIDYR_CONC.txt
        RCP3PD_MIDYR_CONC: RCP3PD_MIDYR_CONC.txt
        RCP45_MIDYR_CONC: RCP45_MIDYR_CONC.txt
        RCP6_MIDYR_CONC: RCP6_MIDYR_CONC.txt
        RCP85_MIDYR_CONC: RCP85_MIDYR_CONC.txt
        C11CLIM: ifsdata/C11CLIM
        C12CLIM: ifsdata/C12CLIM 
        C22CLIM: ifsdata/C22CLIM
        CCL4CLIM: ifsdata/CCL4CLIM
        CH4CLIM: ifsdata/CH4CLIM
        CO2CLIM: ifsdata/CO2CLIM
        ECOZC: ifsdata/ECOZC
        GCH4CLIM: ifsdata/GCH4CLIM
        GCO2CLIM: ifsdata/GCO2CLIM
        GOZOCLIM: ifsdata/GOZOCLIM
        MCICA: ifsdata/MCICA
        N2OCLIM: ifsdata/N2OCLIM
        NO2CLIM: ifsdata/NO2CLIM
        OZOCLIM: ifsdata/OZOCLIM 
        RADRRTM: ifsdata/RADRRTM
        RADSRTM: ifsdata/RADSRTM


namelist_changes:
        fort.4:
                NAMRES:
                        NFRRES: ${before_step}
                        
                NAMPAR0:
                        NPROC: ${oifs.nproca}
                        
                NAMDYN:
                        TSTEP: ${oifs.time_step}
                        
                NAMCT0:
                        CNMEXP: ${oifs.expid}
                        NSTOP: ${oifs.next_step}

foci_fields: [AIceFrac, A_SSTSST, A_TepIce, A_IceTck, A_SnwTck, A_OCurx1, A_OCury1, A_OTaux1, A_OTauy1, A_ITaux1, A_ITauy1, A_QsrIce, A_QsrMix, A_QnsIce, A_QnsMix, ATotRain, ATotSnow, AIceEvap, A_dQnsdT]
# TODO: CSW source and target fields are listed here, this is probably wrong 
# This is an quick-and-dirty fix to test the compilation of FOCI-OIFS
# I'm sure this does not work as the vars in runoff_fields are on different grids.
# To be solved with Dirk.
runoff_fields: [A_Runoff, R_Runoff_atm, O_Runoff, R_Runoff_oce]

coupling_fields:
        "[[foci_fields-->FIELD]]":
                grid: atmo
# TODO: CSW grid info for runoff mapper
        "[[runoff_fields-->FIELD]]":
                grid: atmo

grids:
        atmo:
                name: atmo
                nx: "${nx}"
#                ny: "${_ny}"
#                oasis_grid_type: "D"
                
choose_output:
        "default":
                namelist_changes:
                        fort.4:
                                NAMCT0:
                                        NFRPOS: 6
                                        NFRHIS: 6
                                
        "12hr":
                namelist_changes:
                        fort.4:
                                NAMCT0:
                                        NFRPOS: 12
                                        NFRHIS: 12
                                
                        



choose_version:
        40r1:
                environment_changes:
                        add_export_vars:        
                                - 'OIFS_FFIXED="-fixed"' 

        43r3:
                environment_changes:
                        add_export_vars:        
                                - 'OIFS_FFIXED=""'
                                - 'OIFS_OASIS_BASE="${general.model_dir}"'
                                - 'OIFS_OASIS_INCLUDE="-I$OIFS_OASIS_BASE/build/lib/psmile -I$OIFS_OASIS_BASE/build/lib/psmile/scrip -I$OIFS_OASIS_BASE/build/lib/psmile/mct -I$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu"'
                                - 'OIFS_OASIS_LIB="-L$OIFS_OASIS_BASE/build/lib/psmile -L$OIFS_OASIS_BASE/build/lib/psmile/scrip -L$OIFS_OASIS_BASE/build/lib/psmile/mct -L$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'

