# PISM YAML DEFAULT CONFIGURATION FILE:

model: pism
repository: https://github.com/pism/pism.git
type: ice

standalone_model: True

metadata:
        Institute: UAF and PIK
        Description:
                The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.
        Authors: Ed Bueler, Jed Brown, Anders Levermann, Ricarda Winkelmann and many more (uaf-pism@alaska.edu)
        Publications:
                | Shallow shelf approximation as a “sliding law” in a thermomechanically coupled ice sheet model
                <https://doi.org/10.1029/2008JF001179>
                | The Potsdam parallel ice sheet model (PISM-PIK) - Part 1: Model description
                <https://doi.org/10.5194/tc-5-715-2011>
        License:
                GPL 3.0

description: |
        The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.

license_text: |
        "GPL 3.0"

executable: pismr
version: 1.1.4
domain: "greenland"
resolution: 20km
lresume: false

parent_date: 22941231
parent_expid: khw0030
parent_dir: "${pool_dir}/MPIESM/restart/dev/${parent_expid}/restart/echam6"


# default directories

model_dir: "${general.esm_master.dir}/pism-${version}"
setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
pool_dir: "${computer.pool_directories.pool}/pool_pism"


choose_domain:
        "greenland":
                choose_resolution:
                        20km:
                                - a
                                - b
                                - c
        "nhem":
                choose_resolution:
                        20km:
                                - a
                                - b
                                - b
choose_resolution:
        T63:
                levels: "L47"
                time_step: 450
                _nx: 192
                _ny: 96
                choose_computer.cores_per_node:
                        24:
                                nproca: 24
                                nprocb: 18
                        36:
                                nproca: 24
                                nprocb: 18
        T31:
                levels: "L19"
                time_step: 450
                _nx: 96
                _ny: 48
        T127:
                levels: "L47"
                time_step: 200
                _nx: 384
                _ny: 192

bin_files:
        "pism_bin": "pism_bin"
bin_sources:
        "pism_bin": "${bin_dir}/pismr"
bin_in_work:
        "pism_bin": "pismr"

input_files:
        "cldoptprops": "cldoptprops"
        "janspec": "janspec"
        "jansurf": "jansurf"
        "rrtmglw": "rrtmglw"
        "rrtmgsw": "rrtmgsw"
        "tslclim": "tslclim"
        "vgratclim": "vgratclim"
        "vltclim": "vltclim"

input_in_work:
        "cldoptprops": "ECHAM6_CldOptProps.nc"
        "janspec": "unit.23"
        "jansurf": "unit.24"
        "rrtmglw": "rrtmg_lw.nc"
        "rrtmgsw": "rrtmg_sw.nc"
        "tslclim": "unit.92"
        "vgratclim": "unit.91"
        "vltclim": "unit.90"
        "MAC-SP": "MAC-SP.nc"

forcing_in_work:
        sic: "unit.96"
        sst: "unit.20"
        aerocoarse: "aero_coarse_@YEAR@.nc"
        aerofin: "aero_fine_@YEAR@.nc"
        aerofarir: "aero_farir_@YEAR@.nc"
        ozone: "ozon@YEAR@"
        greenhouse: "greenhouse_gases.nc"
        volcir: "strat_aerosol_ir_@YEAR@.nc"
        volcsw: "strat_aerosol_sw_@YEAR@.nc"
        volcsw: "strat_aerosol_sw_@YEAR@.nc"
        swflux: "swflux_@YEAR@.nc"

ignore_files:
        "[[streams-->STREAM]]": STREAM
        "[[streams-->STREAM]]_restart": STREAM_restart
        "[[streams-->STREAM]]_codes": STREAM_codes

ignore_sources:
        "[[streams-->STREAM]]": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM
        "[[streams-->STREAM]]_restart": restart_${general.expid}_STREAM.nc
        "[[streams-->STREAM]]_codes": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM.codes

ignore_in_workdir:
        "[[streams-->STREAM]]": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM
        "[[streams-->STREAM]]_restart": restart_${general.expid}_STREAM.nc
        "[[streams-->STREAM]]_codes": ${general.expid}_${next_date!syear!smonth}.${next_date!sday}_STREAM.codes

outdata_files: 
        "[[streams-->STREAM]]": STREAM
        "[[streams-->STREAM]]_codes": STREAM_codes

outdata_sources:
        "[[streams-->STREAM]]": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM
        "[[streams-->STREAM]]_codes": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM.codes

outdata_in_workdir:
        "[[streams-->STREAM]]": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM
        "[[streams-->STREAM]]_codes": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM.codes

restart_out_files:
        "[[streams-->STREAM]]": STREAM

restart_out_sources:
        "[[streams-->STREAM]]": restart_${general.expid}_${other_date!syear!smonth!sday!shour!sminute!ssecond}_STREAM.nc

restart_out_in_workdir:
        "[[streams-->STREAM]]": restart_${general.expid}_${other_date!syear!smonth!sday!shour!sminute!ssecond}_STREAM.nc

# Configuration Files:
config_sources:
        "pism_config.nc": "${namelist_dir}/namelist.echam"

config_generate:
        "pism_overrides.nc": null

errors:
        mo_exception:
                check_frequency: 300
                detection_method: "<--grep(mo_exeption.f90)-- standard_out"
                error_message: |
                        !!! DETECTED ERROR !!!
                        Problem with echam >> mo_exception.f90 << has occured. Killing your job, sorry.
                action_method:
                        - "<--kill_job--"

        wind_speed:
                check_frequency: 300
                detection_method: "<--grep(wind speed)-- standard_out"
                error_message: |
                        !!! DETECTED ERROR !!!
                        high wind speed was found during your run, applying wind speed fix and resubmitting...
                action_method:
                        - "<--repair_job_after_windspeed--"

